### ISSUE TITLE
remove index.js files

### ISSUE THREAD

**Issue by vadekh** [digitallinguistics/app#254]
We have decided that the use of index files to combine groups of files for exporting purposes is not required. This process should be as simple as deleting the files, but the comments might actually need updating so that the developer docs continue generating correctly.

**Comment by dwhieb** [comment]
In the JS library, we do want to keep the `index.js` files, because that gives our end users another way to use / import parts of the library, if they want.

For the app though, since we're the ones using it, I don't think we need the `index.js` files.

So I transferred this issue from the JS repo to the app repo.

**Comment by dwhieb** [comment]
Oops, turns out this is a duplicate of #246 anyway.
