### ISSUE TITLE
notes not saving

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#370]
When adding a new note to the Additional Notes, the note is not saved after page refresh.

**Comment by vadekh** [comment]
@dwhieb I think I can handle this one. Looks to me like this is as simple as saving the `Notes`. I think  `additionalNames.js` needs to listen for an update to the `NotesList` and then save the `Notes`

**Comment by dwhieb** [comment]
@vadekh Ok great! And yeah, I think that's exactly right: NotesList should emit an `update` event that the AdditionalNotes component listens for.

**Comment by vadekh** [comment]
@dwhieb It seems to me that we should test Note behavior at a higher level than just the component itself. Do we want to test it from the parent's perspective (i.e. in `AdditionalNames.component.js`), or do we want to test it from the grandparent's perspective (i.e. in `LanguageEditor.e2e.js`), or in both of those places? Or do we want to make an `AdditionalNames.e2e.js` file for these types of tests since we want to test persistence behavior after saves across reloads/rerenders?

**Comment by dwhieb** [comment]
@vadekh The general strategy is to test at the lowest level possible for any given piece of functionality, both in terms of the view hierarchy and the testing hierarchy, and only go up a level when necessary.

Here's how I see that working for notes, from highest to lowest part of the hierarchy:

* each parent of the Notes List: check that the notes save correctly
* Notes List: add/delete notes; check that the Notes List UI works as expected
* Note component tests: edit/update individual note; check that Note UI works as expected

**Comment by vadekh** [comment]
I am moving the testing issue to #437
