### ISSUE TITLE
Home Page overflows on small screens

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#383]
Some part of the Home page is causing overflow on small screens:

![image](https://user-images.githubusercontent.com/5892997/137598872-c823610c-7a56-41f7-8b8f-e20a4d843ce7.png)

**Comment by vadekh** [comment]
@dwhieb The problem here is that the `main` element width is set to `100%`, but the `Home Page` text uses padding in addition to the `main` element. So on small screens, the `main` element is set to match the banner and screen width etc, but then padding is added to that element pushing it beyond the 100% width. I think we can just remove the `width: 100%` from `main` in `App.less`, since we do want the padding on the `Home Page` text. In my initial checks, that does not seem to break anything else style-wise.
